version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      aws:
        patterns:
          - "github.com/aws/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: "/infra/terraform"
    schedule:
      interval: weekly
