{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "optiqor-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optiqor-agent.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "optiqor-agent.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ default "30s" .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ default "10s" .Values.metrics.serviceMonitor.scrapeTimeout }}
      honorLabels: false
{{- end }}
